const URL="https://osawhwcddovhddrxgfju.supabase.co", KEY="sb_publishable_AMGEh3TguYyEpd7piWIjTQ_oHlYdG8f";
let accessToken=localStorage.getItem("v261_access_token")||"";
const $=id=>document.getElementById(id);
function fail(e){$("error").hidden=false;$("error").textContent="エラー: "+(e?.message||e)}
async function req(path,options={}){const headers=Object.assign({apikey:KEY,"Content-Type":"application/json"},options.headers||{});if(accessToken)headers.Authorization="Bearer "+accessToken;const r=await fetch(URL+path,Object.assign({},options,{headers}));const t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error((d&&d.message)||(d&&d.error_description)||t||("HTTP "+r.status));return d}
async function rpc(name,body={}){return req('/rest/v1/rpc/'+name,{method:'POST',body:JSON.stringify(body)})}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function load(){try{$("error").hidden=true;const rows=await rpc('admin_list_redemptions',{});$("gate").hidden=true;$("panel").hidden=false;const list=Array.isArray(rows)?rows:[];$("pendingCount").textContent=list.filter(x=>x.status==='pending').length+'件';$("paidCount").textContent=list.filter(x=>x.status==='paid').length+'件';$("requests").innerHTML=list.length?list.map(x=>`<article class="request"><div><div class="meta"><span>#${x.id}</span><span>${esc(new Date(x.created_at).toLocaleString('ja-JP'))}</span><span>${x.amount}円</span></div><div class="dest">PayPay受取先：${esc(x.payout_destination)}</div><div class="status ${x.status==='paid'?'paid':'pending'}">${x.status==='paid'?'✓ 支払済み':'● 処理待ち'}</div>${x.status==='paid'&&x.completed_at?`<div class="paid-at">支払完了：${esc(new Date(x.completed_at).toLocaleString('ja-JP'))}</div>`:''}</div>${x.status==='pending'?`<button class="paid-btn" data-id="${x.id}" data-amount="${x.amount}" data-dest="${esc(x.payout_destination)}">支払済みにする</button>`:''}</article>`).join(''):'<div class="card">交換申請はまだありません。</div>';document.querySelectorAll('.paid-btn').forEach(b=>b.onclick=()=>markPaid(Number(b.dataset.id),Number(b.dataset.amount),b.dataset.dest,b));}catch(e){$("gateMsg").textContent='管理者として確認できませんでした。';fail(e)}}
async function markPaid(id,amount,dest,b){const ok=confirm('【最終確認】\n\n申請 #'+id+'\n送金額：'+amount+'円\nPayPay受取先：'+dest+'\n\nPayPayでの送金は完了しましたか？\n※この操作は送金完了後にだけ実行してください。');if(!ok)return;b.disabled=true;try{await rpc('admin_mark_redemption_paid',{p_request_id:id});await load()}catch(e){fail(e);b.disabled=false}}
$("reload").onclick=load;load();
